TWEAK_NAME = Quart17UIKit
Quart17UIKit_FILES = Tweak.xm Components.xm ../shared/QGlassCore.m ../shared/QGlassRefraction.mm
Quart17UIKit_CFLAGS = -fobjc-arc -I../shared
Quart17UIKit_FRAMEWORKS = UIKit QuartzCore
Quart17UIKit_LIBRARIES = substrate

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
